### ISSUE TITLE
atlasno

### ISSUE THREAD

**Issue by fkanehiro** [fkanehiro/simtrans#27]
@yosuke さん、いつの間にか変換がうまくいかなくなっているようです。
* atlasのモデルを $ simtrans -i /tmp/atlas.urdf -o /tmp/atlas.wrlとして変換しても、atlas.wrlは生成されない。
* cnoidファイルを見るとatlas-pervis.wrlを開けば良さそうに見えるので開いてみると、head_hokuyo_jointが未定義であると言われる

**Comment by yosuke** [comment]
複雑な構造のsdfへの対応でコア部分含めてかなりいじった関係でurdfなどは動作がおかしくなってしまっています。

atlasの変換に関してはsdfの複数オブジェクトへの対応でroot linkを見つけるロジックをいじったのですが、atlasモデルであえて未解決になっているhokuyo_jointがroot linkとして誤検出されてしまい、それしか変換されなくなってしまったようですね。

sdfへの対応で絶対座標を使うようになった関係で全体を書き直しているところなのですが、書き直しが一段落したところでもろもろチェックします。

**Comment by yosuke** [comment]
下のバージョンであれば動くと思いますので、お急ぎでしたらハッシュ値でgit checkoutして使ってください。

e0c4273abb3c62663d3b0b1755ad52240394cf51

こういうことがあると、バージョンのタグ付けも考えたほうが良さそうですね、、、。

**Comment by yosuke** [comment]
Atlasについては #28 で治ったと思うのですが、PR2の変換がまだ壊れている（閉リンクの部分をfreeのオブジェクトとして誤検出してしまっている）ので、そちらも直します。
