### ISSUE TITLE
simtransで変換したｗｒｌをchoreonoidで使う場合にエラーが出る

### ISSUE THREAD

**Issue by 51ozaki** [fkanehiro/simtrans#68]
simtransを使ったURDFからwrlへの変換について質問させていただきます．

simtransで変換したｗｒｌをchoreonoidで使う場合にエラーで表示できません．
以下の様なエラーが出ます．

OpenHRP モデルファイル "/home/mechatropc-10/catkin_ws/src/crawler_description/VRML/crawler.wrl" を読み込み中
The entity of a to node does not correctly begin with '{' at line 180 of /home/mechatropc-10/catkin_ws/src/crawler_description/VRML/crawler.wrl
 -> 失敗.

エラーメッセージ通り確認したのですが，それらしい間違いは見当たりません．
また，このURDFはRvizでは表示できます．

以下にURDFを記載します．

URDFデータ

<?xml version="1.0"?>
<robot name="crawler">

  <link name="crawler_body">
    <visual>
      <geometry>
        <mesh filename="package://crawler_description/mesh/DAE/crawler_body.dae"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0.06"/>
    </visual>

    <collision>
    
        <geometry>
            <mesh filename="package://crawler_description/mesh/DAE/crawler_body.dae"/>
        </geometry>
       <origin rpy="0 0 0" xyz="0 0 0.06"/>
      </collision>

      <inertial>
  
           <mass value="17" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                           iyy="1.0" iyz="-1.0"
                           izy="1.0" izz="1.0" />
            <origin rpy="0 0 0" xyz="0 0 0.06"/>
      </inertial>

</link>

  <link name="crawler_L">
     <visual>
        <geometry>
         <mesh filename="package://crawler_description/mesh/DAE/crawler.dae"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>

   <collision>
 
        <geometry>
       <mesh filename="package://crawler_description/mesh/DAE/crawler.dae"/>
      </geometry>
     <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
 
    <inertial>
  
              <mass value="1" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                           iyy="1.0" iyz="0.0"
                                     izz="1.0" />
         <origin rpy="0 0 0" xyz="0 0 0"/>
      </inertial>
 </link>

  <link name="crawler_R">
    <visual>
      <geometry>
         <mesh filename="package://crawler_description/mesh/DAE/crawler.dae"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>

    <collision>
   
           <geometry>
              <mesh filename="package://crawler_description/mesh/DAE/crawler.dae"/>
          </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
   </collision>

    <inertial>
   
          <mass value="1" />
           <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                              iyy="1.0" iyz="0.0"
                                        izz="1.0" />
          <origin rpy="0 0 0" xyz="0 0 0"/>
      </inertial>
 </link>

  <link name="flipper_L1">
    <visual>
      <geometry>
        <mesh filename="package://crawler_description/mesh/DAE/flipper.dae"/>
      </geometry>
      <origin rpy="0 0 1.57" xyz="0 0 0.09"/>
    </visual>
 
     <collision>
   
         <geometry>
         <mesh filename="package://crawler_description/mesh/DAE/flipper.dae"/>
        </geometry>
       <origin rpy="0 0 1.57" xyz="0 0 0.09"/>
    </collision>
 
      <inertial>
      
            <mass value="1" />
         <inertia ixx="1.0" ixy="0.0" ixz="1.0"
                           iyy="1.0" iyz="0.0"
                                      izz="1.0" />
        <origin rpy="0 0 1.57" xyz="0 0 0.09"/>
     </inertial>
</link>

p

  <link name="flipper_L2">
    <visual>
      <geometry>
        <mesh filename="package://crawler_description/mesh/DAE/flipper.dae"/>
      </geometry>
      <origin rpy="0 0 1.57" xyz="0 0 0.09"/>
   </visual>

    <collision>
 
         <geometry>
         <mesh filename="package://crawler_description/mesh/DAE/flipper.dae"/>
       </geometry>
<origin rpy="0 0 1.57" xyz="0 0 0.09"/>
    </collision>
 
    <inertial>
  
            <mass value="1" />
        <inertia ixx="1.0" ixy="0.0" ixz="1.0"
                          iyy="1.0" iyz="0.0"
                                     izz="1.0" />
<origin rpy="0 0 1.57" xyz="0 0 0.09"/>
       </inertial>
</link>

  <link name="flipper_R1">
     <visual>
         <geometry>
           <mesh filename="package://crawler_description/mesh/DAE/flipper.dae"/>
         </geometry>
        <origin rpy="0 0 1.57" xyz="0 0 0.09"/>
     </visual>

    <collision>
   
            <geometry>
             <mesh filename="package://crawler_description/mesh/DAE/flipper.dae"/>

           </geometry>
<origin rpy="0 0 1.57" xyz="0 0 0.09"/>
       </collision>
 
      <inertial>
       
              <mass value="1" />
           <inertia ixx="1.0" ixy="0.0" ixz="1.0"
                             iyy="1.0" iyz="0.0"
                                        izz="1.0" />
<origin rpy="0 0 1.57" xyz="0 0 0.09"/>
      </inertial>
</link>

    <link name="flipper_R2">
        <visual>
          <geometry>
            <mesh filename="package://crawler_description/mesh/DAE/flipper.dae"/>
         </geometry>
      <origin rpy="0 0 1.57" xyz="0 0 0.09"/>
    </visual>

   <collision>
    
         <geometry>
          <mesh filename="package://crawler_description/mesh/DAE/flipper.dae"/>

       </geometry>
 <origin rpy="0 0 1.57" xyz="0 0 0.09"/>
   </collision>
 
    <inertial>
        
             <mass value="1" />
        <inertia ixx="1.0" ixy="0.0" ixz="1.0"
                          iyy="1.0" iyz="0.0"
                                     izz="1.0" />
<origin rpy="0 0 1.57" xyz="0 0 0.09"/>
     </inertial>
</link>

  <joint name="crawler_body_to_crawler_L" type="continuous">
    <parent link="crawler_body"/>
    <child link="crawler_L"/>
    <axis xyz="0 1 0"/>
    <origin xyz="0 0.175 0.06"/>
  </joint>

  <joint name="crawler_body_to_crawler_R" type="continuous">
    <parent link="crawler_body"/>
    <child link="crawler_R"/>
    <axis xyz="0 1 0"/>
    <origin xyz="0 -0.175 0.06"/>
  </joint>

  <joint name="crawler_L to flipper_L1" type="continuous">
    <parent link="crawler_L"/>
    <child link="flipper_L1"/>
    <axis xyz="0 1 0"/>
    <origin xyz="0.23 0.04 0"/>
  </joint>

  <joint name="crawler_L to flipper_L2" type="continuous">
    <parent link="crawler_L"/>
    <child link="flipper_L2"/>
    <axis xyz="0 1 0"/>
    <origin xyz="-0.23 0.04 0"/>
  </joint>

  <joint name="crawler_R to flipper_R1" type="continuous">
    <parent link="crawler_R"/>
    <child link="flipper_R1"/>
    <axis xyz="0 1 0"/>
    <origin xyz="0.23 -0.04 0"/>
  </joint>

  <joint name="crawler_R to flipper_R2" type="continuous">
    <parent link="crawler_R"/>
    <child link="flipper_R2"/>
    <axis xyz="0 1 0"/>
    <origin xyz="-0.23 -0.04 0"/>
  </joint>

</robot>

**Comment by 51ozaki** [comment]
以下が変換したｗｒｌです。


#VRML V2.0 utf8

PROTO Joint [
  exposedField     SFVec3f      center              0 0 0
  exposedField     MFNode       children            []
  exposedField     MFFloat      llimit              []
  exposedField     MFFloat      lvlimit             []
  exposedField     SFRotation   limitOrientation    0 0 1 0
  exposedField     SFString     name                ""
  exposedField     SFRotation   rotation            0 0 1 0
  exposedField     SFVec3f      scale               1 1 1
  exposedField     SFRotation   scaleOrientation    0 0 1 0
  exposedField     MFFloat      stiffness           [ 0 0 0 ]
  exposedField     SFVec3f      translation         0 0 0
  exposedField     MFFloat      ulimit              []
  exposedField     MFFloat      uvlimit             []
  exposedField     SFString     jointType           ""
  exposedField     SFInt32      jointId             -1
  exposedField     SFVec3f      jointAxis           0 0 1

  exposedField     SFFloat      gearRatio           1
  exposedField     SFFloat      rotorInertia        0
  exposedField     SFFloat      rotorResistor       0
  exposedField     SFFloat      torqueConst         1
  exposedField     SFFloat      encoderPulse        1
]
{
  Transform {
    center           IS center
    children         IS children
    rotation         IS rotation
    scale            IS scale
    scaleOrientation IS scaleOrientation
    translation      IS translation
  }
}

PROTO Segment [
  field           SFVec3f     bboxCenter        0 0 0
  field           SFVec3f     bboxSize          -1 -1 -1
  exposedField    SFVec3f     centerOfMass      0 0 0
  exposedField    MFNode      children          [ ]
  exposedField    SFNode      coord             NULL
  exposedField    MFNode      displacers        [ ]
  exposedField    SFFloat     mass              0
  exposedField    MFFloat     momentsOfInertia  [ 0 0 0 0 0 0 0 0 0 ]
  exposedField    SFString    name              ""
  eventIn         MFNode      addChildren
  eventIn         MFNode      removeChildren
]
{
  Group {
    addChildren    IS addChildren
    bboxCenter     IS bboxCenter
    bboxSize       IS bboxSize
    children       IS children
    removeChildren IS removeChildren
  }
}

PROTO Surface [
 field   SFVec3f bboxCenter 0 0 0
 field   SFVec3f bboxSize   -1 -1 -1
 field   MFNode  visual     [ ]
 field   MFNode  collision  [ ]
 eventIn MFNode  addChildren
 eventIn MFNode  removeChildren
]
{
  Group {
    addChildren    IS addChildren
    bboxCenter     IS bboxCenter
    bboxSize       IS bboxSize
    children       IS visual
    removeChildren IS removeChildren
  }
}

PROTO Humanoid [
  field           SFVec3f    bboxCenter            0 0 0
  field           SFVec3f    bboxSize              -1 -1 -1
  exposedField    SFVec3f    center                0 0 0
  exposedField    MFNode     humanoidBody          [ ]
  exposedField    MFString   info                  [ ]
  exposedField    MFNode     joints                [ ]
  exposedField    SFString   name                  ""
  exposedField    SFRotation rotation              0 0 1 0
  exposedField    SFVec3f    scale                 1 1 1
  exposedField    SFRotation scaleOrientation      0 0 1 0
  exposedField    MFNode     segments              [ ]
  exposedField    MFNode     sites                 [ ]
  exposedField    SFVec3f    translation           0 0 0
  exposedField    SFString   version               "1.1"
  exposedField    MFNode     viewpoints            [ ]
]
{
  Transform {
    bboxCenter       IS bboxCenter
    bboxSize         IS bboxSize
    center           IS center
    rotation         IS rotation
    scale            IS scale
    scaleOrientation IS scaleOrientation
    translation      IS translation
    children [
      Group {
        children IS viewpoints
      }
    ]
  }
}

PROTO ExtraJoint [
  exposedField SFString link1Name ""
  exposedField SFString link2Name ""
  exposedField SFVec3f  link1LocalPos 0 0 0
  exposedField SFVec3f  link2LocalPos 0 0 0
  exposedField SFString jointType "xyz"
  exposedField SFVec3f  jointAxis 1 0 0
]
{
}



DEF crawler_body Humanoid {
  humanoidBody [
    DEF crawler_body Joint {
      jointType "free"
      translation 0.0 0.0 0.0
      rotation 0 1 0 0
      children [
        DEF crawler_body Segment {
          mass 17.0
          centerOfMass 0.0 0.0 0.06
          momentsOfInertia [1.0 0.0 0.0 0.0 1.0 -1.0 0.0 -1.0 1.0]
          children [
            Transform {
              scale 1.0 1.0 1.0
              translation 0.0 0.0 0.06
              rotation 0 1 0 0
              children [
                Inline {
                  url "crawler-crawler_body-crawler-crawler_body_visual.wrl"
                }
              ]
            }
          ]
        }
            
        DEF crawler_body_to_crawler_L Joint {
          jointType "rotate"
          jointAxis 0.0 1.0 0.0
          jointId 2
          translation 0.0 0.175 0.06
          rotation 0 1 0 0
          ulimit 1e+16
          llimit -1e+16
          uvlimit inf
          lvlimit -inf
          children [
            DEF crawler_L Segment {
              mass 1.0
              centerOfMass 0.0 0.0 0.0
              momentsOfInertia [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0]
              children [
                Transform {
                  scale 1.0 1.0 1.0
                  translation 0.0 0.0 0.0
                  rotation 0 1 0 0
                  children [
                    Inline {
                      url "crawler-crawler_L-crawler-crawler_L_visual.wrl"
                    }
                  ]
                }
              ]
            }
                
            DEF crawler_L to flipper_L1 Joint {
              jointType "rotate"
              jointAxis 0.0 1.0 0.0
              jointId 0
              translation 0.23 0.04 1.2490009027e-16
              rotation 0 1 0 0
              ulimit 1e+16
              llimit -1e+16
              uvlimit inf
              lvlimit -inf
              children [
                DEF flipper_L1 Segment {
                  mass 1.0
                  centerOfMass 0.0 0.0 0.09
                  momentsOfInertia [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0]
                  children [
                    Transform {
                      scale 1.0 1.0 1.0
                      translation 0.0 0.0 0.09
                      rotation -0.0 -0.0 1.0 1.57
                      children [
                        Inline {
                          url "crawler-flipper_L1-crawler-flipper_L1_visual.wrl"
                        }
                      ]
                    }
                  ]
                }
                    
              ]
            }
            DEF crawler_L to flipper_L2 Joint {
              jointType "rotate"
              jointAxis 0.0 1.0 0.0
              jointId 1
              translation -0.23 0.04 1.2490009027e-16
              rotation 0 1 0 0
              ulimit 1e+16
              llimit -1e+16
              uvlimit inf
              lvlimit -inf
              children [
                DEF flipper_L2 Segment {
                  mass 1.0
                  centerOfMass 0.0 0.0 0.09
                  momentsOfInertia [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0]
                  children [
                    Transform {
                      scale 1.0 1.0 1.0
                      translation 0.0 0.0 0.09
                      rotation -0.0 -0.0 1.0 1.57
                      children [
                        Inline {
                          url "crawler-flipper_L2-crawler-flipper_L2_visual.wrl"
                        }
                      ]
                    }
                  ]
                }
                    
              ]
            }
          ]
        }
        DEF crawler_body_to_crawler_R Joint {
          jointType "rotate"
          jointAxis 0.0 1.0 0.0
          jointId 5
          translation 0.0 -0.175 0.06
          rotation 0 1 0 0
          ulimit 1e+16
          llimit -1e+16
          uvlimit inf
          lvlimit -inf
          children [
            DEF crawler_R Segment {
              mass 1.0
              centerOfMass 0.0 0.0 0.0
              momentsOfInertia [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0]
              children [
                Transform {
                  scale 1.0 1.0 1.0
                  translation 0.0 0.0 0.0
                  rotation 0 1 0 0
                  children [
                    Inline {
                      url "crawler-crawler_R-crawler-crawler_R_visual.wrl"
                    }
                  ]
                }
              ]
            }
                
            DEF crawler_R to flipper_R1 Joint {
              jointType "rotate"
              jointAxis 0.0 1.0 0.0
              jointId 3
              translation 0.23 -0.04 1.2490009027e-16
              rotation 0 1 0 0
              ulimit 1e+16
              llimit -1e+16
              uvlimit inf
              lvlimit -inf
              children [
                DEF flipper_R1 Segment {
                  mass 1.0
                  centerOfMass 0.0 0.0 0.09
                  momentsOfInertia [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0]
                  children [
                    Transform {
                      scale 1.0 1.0 1.0
                      translation 0.0 0.0 0.09
                      rotation -0.0 -0.0 1.0 1.57
                      children [
                        Inline {
                          url "crawler-flipper_R1-crawler-flipper_R1_visual.wrl"
                        }
                      ]
                    }
                  ]
                }
                    
              ]
            }
            DEF crawler_R to flipper_R2 Joint {
              jointType "rotate"
              jointAxis 0.0 1.0 0.0
              jointId 4
              translation -0.23 -0.04 1.2490009027e-16
              rotation 0 1 0 0
              ulimit 1e+16
              llimit -1e+16
              uvlimit inf
              lvlimit -inf
              children [
                DEF flipper_R2 Segment {
                  mass 1.0
                  centerOfMass 0.0 0.0 0.09
                  momentsOfInertia [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0]
                  children [
                    Transform {
                      scale 1.0 1.0 1.0
                      translation 0.0 0.0 0.09
                      rotation -0.0 -0.0 1.0 1.57
                      children [
                        Inline {
                          url "crawler-flipper_R2-crawler-flipper_R2_visual.wrl"
                        }
                      ]
                    }
                  ]
                }
                    
              ]
            }
          ]
        }
      ]
    }
  ]
  joints [
    USE crawler_L to flipper_L1,
    USE crawler_L to flipper_L2,
    USE crawler_body_to_crawler_L,
    USE crawler_R to flipper_R1,
    USE crawler_R to flipper_R2,
    USE crawler_body_to_crawler_R
  ]
  
  name "crawler_body"
  version "1.0"
}

**Comment by fkanehiro** [comment]
Joint名にスペースが入っているようですので、これをやめてみて頂けますでしょうか。

**Comment by 51ozaki** [comment]
すみません

どのjointにスペースが入っているのでしょうか

**Comment by fkanehiro** [comment]
crawler_L to flipper_L1
crawler_L to flipper_L2
crawler_R to flipper_R1
crawler_R to flipper_R2
です。

**Comment by 51ozaki** [comment]
表示できました．
お手数おかけしました，ありがとうございます．
