### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by qbrobotics-AT** [fkanehiro/simtrans#73]
Hi,

First of all I want to thank you for all your efforts in this project which I is very helpful in a world without automatic export tools to/from URDF/SDF.

Nonetheless, I'm still trying to install `simtrans` but I have found two problems and I cannot proceed. I'm following this [documentation](http://fkanehiro.github.io/simtrans/html/install.html)) and my setup is the following: _Ubuntu 16.04 with ROS Kinetic and Gazebo 7.1_.

1. With ROS Kinetic installed, when trying to install `openhrp` it fails because it depends on `collada-dom2.4-dp-base` (version 2.4.3), but I found `libcollada-dom2.4-dp-dev` (version 2.4.4) already installed and it obviously throw an exception.

   I don't know if it is the right thing to do, but I installed `ros-kinetic-openhrp3` from the package manager because it said that _"This package does not only wrap OpenHRP3 but actually provides the built artifact from the code from its mainstream repository."_.

2. During the final part of the installation process, i.e. when executing `sudo python setup.py install`, the compilation process end with a **`fatal error`** because it has some problem with the `#include <sdf/sdf.hh>`:

       running install
       running bdist_egg
       running egg_info
       writing simtrans.egg-info/PKG-INFO
       writing top-level names to simtrans.egg-info/top_level.txt
       writing dependency_links to simtrans.egg-info/dependency_links.txt
       writing entry points to simtrans.egg-info/entry_points.txt
       reading manifest file 'simtrans.egg-info/SOURCES.txt'
       reading manifest template 'MANIFEST.in'
       writing manifest file 'simtrans.egg-info/SOURCES.txt'
       installing library code to build/bdist.linux-x86_64/egg
       running install_lib
       running build_py
       running build_ext
       building 'simtranssdfhelper' extension
       x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/sdformat-4.2 -I/usr/include/ignition/math2 -I/usr/include/python2.7 -c simtrans/sdfhelper.cpp -o build/temp.linux-x86_64-2.7/simtrans/sdfhelper.o
       cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
       simtrans/sdfhelper.cpp:3:22: fatal error: sdf/sdf.hh: File or directory not found
       compilation terminated.
       error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

   Of course I have already installed `sdformat-4.2` (from Gazebo installation) and it properly includes the right directory: `... -I/usr/include/sdformat-4.2 ...`.
   Therefore I have decided that the problem must be elsewhere. I have investigated a bit more and I found that if I manually compile using `g++` (or `gcc`) with the ` -std=c++11` flag enabled and all the above other settings, it ends with just a couple of warings. Nonetheless, I don't know if the installation process can be consider finished correctly or not. Are there other instruction after the compile command? And, is there a way to switch the default compiler with a custom one?

Thank you for your time,
Alessandro Tondo

**Comment by qbrobotics-AT** [comment]
I really don't know why but if I compile the code this way, the installation seems to complete correctly:

    sudo python setup.py build_ext --include-dirs=/usr/include/sdformat-4.2:/usr/include/ignition/math2
    sudo python setup.py install

Now I'm going to try some conversions to check if the first problem affects the execution or not.

**Comment by fkanehiro** [comment]
Thank you for the report.
I have never tested on the platform. Probably I need some modifications.

**Comment by fkanehiro** [comment]
I have solved the issue by #74.
